hash-format = "sha256"

[[files]]
file = "datapacks/towers-of-the-wild-reworked.pw.toml"
hash = "b70ebb349dffc58c7c7d88cb763a7824fa1bba23bf4010370d388310ebeebe49"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "e3dfb2478e6bb096667d4ec89b0ddfef627747939373bdefee02f358d6e3dee1"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "a243675bc757485925b293932ee289b9fbcfb3b75bd3ba74eca7603f191cedad"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
hash = "45e9ed825929aee685220a3625e94d89c5ba7c91557d2b8050b70c6008de1a7d"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "b25474cd7e4cff1ff70fbcbd1a466aa518850d8fa82da1114667f04a03fc9fff"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "7721e78d990cc15c02f1a03cd6d7652ea995b271a3d19a6ae44829b4c69acbf0"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "31fdd1e2499f295c5806bac01987129f54c0960fdee8dfba5123ac6432bc8f9b"
metafile = true

[[files]]
file = "mods/cherry-villages.pw.toml"
hash = "400f0b0361b711181c6947583bea5b6585afedb1434877f1e1e44f45e72ac56d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a89dfcc985612a275975d4823a24fc3dceb244bacb2e8f81bd459283bf1b9fe9"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "bb7b31de1f5c7941aff59030d59168a5971e8c47884bcd8905637836ff97ce46"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "9a4d1f42d2798dac502f7adcbee9b6691d7e79c50d91b23af11923893a686b8b"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "4ba45966a267b774f5d83442c3c43d740f55e11a910e117e50c046b4f77b5c66"
metafile = true

[[files]]
file = "mods/deeper_dark.pw.toml"
hash = "3967f8b341b036e99bf62b09ba71c47bb889c4bf8e334ea8c76b718aa330eccb"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "ec5f0ed9e8d3b79ea61f7c79127b5f113e23ac96e92f5ba409084c8d0ab7da5e"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "13baf86c7202df729de43ea5ac8766581c39e35651391d080a9a2a33252c2996"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "33f865a014f3acf2c1f2c452bfe7ba1a864acad178322a6eab3759c7e63c9654"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "f6f8827bc39d892a56351a6cecd39176addebb2ebf1c608b761b0d1985080b05"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
hash = "dc4a6ad558baacff8619bcb127784bfa27eb6ca4c177eae12d86b833eca80694"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "39a6a39433b1b104bfafafcd60a8171f866daa2ebefffd64df822d0e69288e3a"
metafile = true

[[files]]
file = "mods/immersive-structures.pw.toml"
hash = "87184da0fbda69dd2d209f9597beca5241893eb32e3e3d07356d1be3afa496b8"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "78f676cf264658e720a6522f12c52af65f536071b73720b0f26f44834c7a0cdc"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "71ef7cc16632c0039fe194183b5885968c6d740aaa67a58000653ae0cb40b882"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "43986085a6a74e456999737d6f3b68f35bacc0d71aa9ee780e8dc143afd181b1"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c239c951796882b9c93e649a0dba4f2d95804441faaed707b686381b7a5c67da"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "bc79745faf3cfec5d60e239817905c2bebfb692f8ae3ff3671fc8afd4800227e"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "4cd171d3f5f3e1d2948cb1b0062e742a5e85110c9e9a668f9aed5b0cebcb9c97"
metafile = true

[[files]]
file = "mods/mouse-wheelie.pw.toml"
hash = "f5eb9d19a205a42dbb9d8ad4ee95e2cf0364814dd8416a9147b21f261dd93c97"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "7ca62a9da5c2ec9f0a8bed5394021c959e90077db16b313be44f4c8736f7fbf5"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
hash = "1f265c12c3649ab889b96bf8a3f5263521e5afc82c66e094983bfd003b3200a2"
metafile = true

[[files]]
file = "mods/nvidium.pw.toml"
hash = "9b5ba0e49c19478f93bef3a4c3ba8f068e4d0039fa643423ef411b9f11621105"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "44b0a2294e1693230308e53b529d671a0303e94b623ba2c2650cdf5760a5a335"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "23d596d1d2e39ae3b05415790663819401fc62d745d6a817e88d9c36d07bce53"
metafile = true

[[files]]
file = "mods/repurposed-structures-fabric.pw.toml"
hash = "698ce298ab211ebb6752f131d32ea8272eff3a419998a1a398e4affe6c7479a7"
metafile = true

[[files]]
file = "mods/saturated.pw.toml"
hash = "6f1f679fa3d6c2a2f857e46eb75779b5320aeb20f81ebfce9ca13075fa1aa660"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "4e691c86059e755a026b8cae8cf0c66396dc39bf47b6c71980589101803ecd36"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "9a927c3e0830ba32e1b8a2e543597781724462595b8cce58f676962b442bb52b"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "218f67d6bcaae849582618cd3e5eb1d4cac0fd6045115f64340620300e160c11"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "d4999aa4a0af3e06221075e4cbf62a8ffdc50537353d494ac40dd73f12bc173c"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "eede133dd250889ed521ba31ace80af20f71d47585a28de1184fe29fde83dad0"
metafile = true

[[files]]
file = "mods/the-graveyard-fabric.pw.toml"
hash = "e23510ac34f83b29895fdefc6397a62f87042a05fb7a358f8433acfdbfa84f52"
metafile = true

[[files]]
file = "mods/the-lost-castle.pw.toml"
hash = "71759ba6675ec4109bc555e2f5adfa5d433d8f633692a1bb69b0c7b2a0b90ae9"
metafile = true

[[files]]
file = "mods/tidal-towns.pw.toml"
hash = "5d3a6812ad065ed4e6d84824d053757ca9f798eb0e0ef9bc8a103aba950022e2"
metafile = true

[[files]]
file = "mods/towers-of-the-wild-additions.pw.toml"
hash = "47960028fa39275a2d9a1c70c27e5a59395d4facfcb1f50529e0286b2d0655c0"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "f4ee188c011337963dc95d3e3c6c76cbd6fccf90c533b09639b490a1129eb522"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "b2e02d1210f025b905299bfc88f895058640158343322641aca2c4875622c992"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "086f56d0a3c8f1a7b289b9949d7de08362f717295d89f0db0d13421ec860a453"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
hash = "97f498b07031e2182b35950117c01d2b5be682ad03a12fedb041e739b9dbd0f9"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "dd76a7b6505ebef5beefd48742509d31be1e232051bf08c32ccabbf88ae9d313"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "f79ac61306ede9d4037235e540fb6f9046a5fa20ef1b24b2639c6ca78addd165"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "9f8a007f79fc9d88ea537a9c3c2db347cc88a3adb84d39d17f12a5921e0291bf"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "b9ffba892e9f541bbffc0fc9dc4360732e9edeb7d2d4560191fc08e457c9d372"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "58de55cfb9a33cb71eb7a50a55d6fdd9cc970fd866e603ab5373c9c3087a6d84"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "2bb58b3921466f6f40b48830415c2e8b6bdacd3b126706ff141014004dad815f"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "717541277779ecae1980c5c62d1ad098c20d41a91e7d14927b86582e7e0914b1"
metafile = true
