name = "Vanilla Adventure"
author = "AmeMeida"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43a6df4b0dd4a8af54c86c6f6a650675c6d437b9e421169ac2778b6ea1e4d06c"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
